development:
  secret_key_base: 729d635ee410d6b282d81408cea1f2101e94128e621ce3fe73d83639eaad44ab0048de9a14b0c7c5f9250572f373a01f5f1541d914c10b900a6ede6fc14faef9 
  # Paste output of $ rake secret here for your dev machine.

test:
  secret_key_base: 729d635ee410d6b282d81408cea1f2101e94128e621ce3fe73d83639eaad44ab0048de9a14b0c7c5f9250572f373a01f5f1541d914c10b900a6ede6fc14faef9

production:
  secret_key_base: 729d635ee410d6b282d81408cea1f2101e94128e621ce3fe73d83639eaad44ab0048de9a14b0c7c5f9250572f373a01f5f1541d914c10b900a6ede6fc14faef9


  STRIPE_PUBLISHABLE_KEY: 'Put your stripe keys for production'
  STRIPE_SECRET_KEY: 'Put actual keys for production here'
  FB_APP_SECRET: 'same as above'
  FB_CALLBACK_URL: 'FB url here'
  FB_CALLBACK_UPDATE_URL: 'FB url here'
  GOOGLE_KEY: 'Put your keys for production'
  GOOGLE_SECRET: 'same as above'
  TWITTER_KEY: 'same as above'
  TWITTER_SECRET: 'same as above'
  TWITTER_USERNAME: 'same as above'
  LINKEDIN_KEY: 'same as above'
  LINKEDIN_SECRET: 'same as above'